select
	DATE_TRUNC('mon', target_date)::DATE AS MONTH,
	SUM(hour) as hour,
	SUM(price_zone_code) as price_zone_code,
	SUM(consumer_max_price) as consumer_max_price,
	SUM(consumer_min_price) as consumer_min_price,
	SUM(consumer_price) as consumer_price,
	SUM(consumer_provide_rd) as consumer_provide_rd,
	SUM(consumer_provide_sdd) as consumer_provide_sdd,
	SUM(consumer_provide_sdemb) as consumer_provide_sdemb,
	SUM(consumer_provide_sdemnb) as consumer_provide_sdemnb,
	SUM(consumer_rd_volume) as consumer_rd_volume,
	SUM(consumer_spot_volume) as consumer_spot_volume,
	SUM(consumer_volume) as consumer_volume,
	SUM(export_max_price) as export_max_price,
	SUM(export_min_price) as export_min_price,
	SUM(export_price) as export_price,
	SUM(export_provide_rd) as export_provide_rd,
	SUM(export_provide_sdd) as export_provide_sdd,
	SUM(export_provide_sdemb) as export_provide_sdemb,
	SUM(export_provide_sdemnb) as export_provide_sdemnb,
	SUM(export_rd_volume) as export_rd_volume,
	SUM(export_spot_volume) as export_spot_volume,
	SUM(export_volume) as export_volume,
	SUM(full_sdd_corr) as full_sdd_corr,
	SUM(full_sdd_without_corr) as full_sdd_without_corr,
	SUM(supplier_max_price) as supplier_max_price,
	SUM(supplier_min_price) as supplier_min_price,
	SUM(supplier_price) as supplier_price,
	SUM(supplier_provide_rd) as supplier_provide_rd,
	SUM(supplier_rd_volume) as supplier_rd_volume,
	SUM(supplier_spot_volume) as supplier_spot_volume,
	SUM(supplier_volume) as supplier_volume,
	count(*) as count_rows
from
	graph.wh_dlh_stats_hourly wdsh
group by 1